[WIP][BREAKING] Transform module to ESM
SAP/ui5-fs pull request #398
Opened 2022-09-13 13:48 UTC by matz3

JIRA: CPOUI5FOUNDATION-525

2022-09-14 07:00 UTC, matz3 commented on package.json
> -		"graceful-fs": "^4.2.9",
I think we use graceful-fs for a reason, so we should keep it

2022-09-26 08:04 UTC, RandomByte commented
> [[BREAKING CHAMGE] AbstractReader: migrate subreader calls to async](https://github.com/SAP/ui5-fs/pull/398/commits/eeefd4c380c6950571f8290ee8e31f5441a65323)

This commit is actually not breaking, since the changed API has only been added in v3 and is not public yet.

2022-09-30 06:35 UTC, flovogt commented
### Open topics:
[ ] Should be `ResourceTagCollection` public and if yes which methods?
[ ] Should be `ResourceFacade` public and if yes which methods?

2022-10-20 14:09 UTC, RandomByte submitted a review, later dismissed

2022-10-21 07:23 UTC, flovogt requested changes

2022-10-21 07:23 UTC, flovogt commented on lib/readers/Transformer.js
> + * @private
We're setting the transformer here to private because we plan to remove this artifact completely in one of the next steps.

2022-10-21 07:23 UTC, flovogt commented on lib/resourceFactory.js
> + * @param {string} [parameters.name]  Name for the reader collection
duplicate space after `[parameters.name]`

2022-10-21 07:23 UTC, flovogt commented on test/lib/fsInterface.js
> +const readFile = promisify(fs.readFile);
`readFile` is already available as promise returning method. Use `import {readFile} from "node:fs/promises";`

2022-10-24 04:45 UTC, flovogt commented on lib/resourceFactory.js
> + * @param {string} [parameters.name]  Name for the reader collection
Done

2022-10-24 04:46 UTC, flovogt commented on lib/readers/Transformer.js
> + * @private
Only a note for anyone who is wondering about 🧙🏽‍♂️

2022-10-24 04:50 UTC, flovogt commented on test/lib/fsInterface.js
> +const readFile = promisify(fs.readFile);
Done

2022-10-24 04:51 UTC, flovogt submitted a review, later dismissed

2022-10-24 09:20 UTC, RandomByte approved these changes

2022-10-24 12:15 UTC, merged