[BREAKING] Clone resources when writing in and reading from the Memory
SAP/ui5-fs pull request #448
Opened 2022-11-29 14:39 UTC by flovogt

Clone resources when writing them in the memory.

JIRA: CPOUI5FOUNDATION-567

Follow-Up of https://github.com/SAP/ui5-fs/pull/259.

2022-12-01 15:10 UTC, RandomByte commented
LGTM

2022-12-02 13:35 UTC, flovogt commented on test/lib/adapters/Memory_write.js
> +	t.is(resources.length, 1, "Found exactly one resource");
call setContent to the written resource and check that original resource is not changed

2022-12-02 13:36 UTC, flovogt commented
Enhance integration test "test/lib/resources.js" to call setContent to the written resource and check that original resource is not changed for both existing adapters

2022-12-02 13:52 UTC, flovogt commented
Cherry-pick "read" PR in this one here and close the other one

2022-12-14 13:37 UTC, flovogt commented on test/lib/adapters/Memory_write.js
> +	t.is(resources.length, 1, "Found exactly one resource");
done

2022-12-14 14:01 UTC, RandomByte requested changes

2022-12-14 14:13 UTC, flovogt commented on test/lib/adapters/Memory_write.js
> +	t.is(await resource2.getString(), "MyNewContent");
Done

2022-12-14 14:14 UTC, RandomByte approved these changes

2022-12-14 14:39 UTC, merged